/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["app/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  theme: {
    extend: {
      colors: {
        darkerGreen: "#749596",
        darkGreen: "#638889",
        heavyGreen: "#85a1a3",
        lightGreen: "#95aeb0",
        surface1: "#121212",
        surface2: "#282828",
        surface3: "#3f3f3f",
      },
      fontFamily: {
        heading: ["var(--font-lilita)"],
        sans: ["var(--font-montserrat)"],
      },
      typography: ({ theme }) => ({
        green: {
          css: {
            "--tw-prose-body": theme("colors.white"),
            "--tw-prose-bold": theme("colors.heavyGreen"),
            "--tw-prose-bullets": theme("colors.darkGreen"),
            "--tw-prose-captions": theme("colors.darkGreen"),
            "--tw-prose-code": theme("colors.lightGreen"),
            "--tw-prose-counters": theme("colors.darkGreen"),
            "--tw-prose-headings": theme("colors.white"),
            "--tw-prose-hr": theme("colors.lightGreen"),
            "--tw-prose-invert-body": theme("colors.pink[200]"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-bullets": theme("colors.darkGreen"),
            "--tw-prose-invert-captions": theme("colors.pink[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.pink[400]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-hr": theme("colors.pink[700]"),
            "--tw-prose-invert-lead": theme("colors.lightGreen"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-pre-bg": theme("colors.heavyGreen"),
            "--tw-prose-invert-pre-code": theme("colors.lightGreen"),
            "--tw-prose-invert-quote-borders": theme("colors.pink[700]"),
            "--tw-prose-invert-quotes": theme("colors.pink[100]"),
            "--tw-prose-invert-td-borders": theme("colors.pink[700]"),
            "--tw-prose-invert-th-borders": theme("colors.darkGreen"),
            "--tw-prose-lead": theme("colors.pink[700]"),
            "--tw-prose-links": theme("colors.darkGreen"),
            "--tw-prose-pre-bg": theme("colors.darkGreen"),
            "--tw-prose-pre-code": theme("colors.pink[100]"),
            "--tw-prose-quote-borders": theme("colors.lightGreen"),
            "--tw-prose-quotes": theme("colors.darkGreen"),
            "--tw-prose-td-borders": theme("colors.pink[200]"),
            "--tw-prose-th-borders": theme("colors.lightGreen"),
          },
        },
      }),
    },
  },
};
