/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["app/**/*.{ts,tsx}", "src/components/**/*.{ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  theme: {
    extend: {
      colors: {
        "dark-green": "#638889",
        darkBlue: "#A3C3D9",
        "darker-green": "#476263",
        "heavy-green": "#557576",
        "light-green": "#9DBC98",
        lightBlue: "#E9ECF5",
        mediumBlue: "#CCD6EB",
        orange: "#e2662c",
        salsa: "#F05D5E",
        tan: "#f9efdb",
      },
      fontFamily: {
        heading: ["var(--font-lilita)"],
        sans: ["var(--font-montserrat)"],
      },
      typography: ({ theme }) => ({
        green: {
          css: {
            "--tw-prose-body": theme("colors.dark-green"),
            "--tw-prose-bold": theme("colors.heavy-green"),
            "--tw-prose-bullets": theme("colors.dark-green"),
            "--tw-prose-captions": theme("colors.dark-green"),
            "--tw-prose-code": theme("colors.light-green"),
            "--tw-prose-counters": theme("colors.dark-green"),
            "--tw-prose-headings": theme("colors.heavy-green"),
            "--tw-prose-hr": theme("colors.light-green"),
            "--tw-prose-invert-body": theme("colors.pink[200]"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-bullets": theme("colors.dark-green"),
            "--tw-prose-invert-captions": theme("colors.pink[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.pink[400]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-hr": theme("colors.pink[700]"),
            "--tw-prose-invert-lead": theme("colors.light-green"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-pre-bg": theme("colors.heavy-green"),
            "--tw-prose-invert-pre-code": theme("colors.light-green"),
            "--tw-prose-invert-quote-borders": theme("colors.pink[700]"),
            "--tw-prose-invert-quotes": theme("colors.pink[100]"),
            "--tw-prose-invert-td-borders": theme("colors.pink[700]"),
            "--tw-prose-invert-th-borders": theme("colors.dark-green"),
            "--tw-prose-lead": theme("colors.pink[700]"),
            "--tw-prose-links": theme("colors.dark-green"),
            "--tw-prose-pre-bg": theme("colors.dark-green"),
            "--tw-prose-pre-code": theme("colors.pink[100]"),
            "--tw-prose-quote-borders": theme("colors.light-green"),
            "--tw-prose-quotes": theme("colors.dark-green"),
            "--tw-prose-td-borders": theme("colors.pink[200]"),
            "--tw-prose-th-borders": theme("colors.light-green"),
          },
        },
      }),
    },
  },
};
