#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

should_run=0

while read -r local_ref local_sha remote_ref remote_sha; do
  if [ "$local_ref" = "refs/heads/main" ]; then
    should_run=1
  fi
done

if [ "$should_run" = "1" ]; then
  node scripts/generate-changelog.mjs
fi
